#ifndef		__DIALOG_PROC_H__
#define		__DIALOG_PROC_H__

INT_PTR CALLBACK ComboListProc(HWND,UINT,WPARAM,LPARAM);
INT_PTR CALLBACK EditProc(HWND,UINT,WPARAM,LPARAM);
INT_PTR CALLBACK TimeZoneProc(HWND,UINT,WPARAM,LPARAM);
INT_PTR CALLBACK ComboEditProc(HWND,UINT,WPARAM,LPARAM);

#endif		//__DIALOG_PROC_H__

